# Generated by Django 4.2.19 on 2025-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group_follow_post_group_follow_unique_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
